import { Reciter, Translation } from '../types';
import { EN_SAHIH_TRANSLATION } from '../data/en_sahih';

// Placeholder for new translation data.
const EN_QARAI_TRANSLATION: Record<string, Record<string, string>> = {};

export const RECITERS: Reciter[] = [
    // Murattal Styles
    { id: 'zephyr', name: 'Female: Murattal (Clear, Teacher-like)', voice: 'Zephyr', stylePrompt: "Recite this Quranic verse as a wise and devout Muslim woman teaching the Quran. The delivery must be in a clear, articulate, and masterfully controlled Murattal style (Tarteel). The voice should be warm, nurturing, and encouraging, yet authoritative in its correctness. It must be imbued with a deep sense of faith and reverence, featuring flawless Tajweed and crisp pronunciation (Makharij). The pace should be measured and steady, avoiding any rush or monotony, allowing each word to resonate with tranquility and clarity for the student. Elongations (Madd) must be natural and perfectly balanced, ensuring the recitation is an ideal model of clarity and understanding: " },
    { id: 'kore', name: 'Female: Murattal (Serene & Reflective)', voice: 'Kore', stylePrompt: "Recite this Quranic verse in a serene, deeply moving, and devotional Murattal style, as if in a personal, intimate prayer (salah). The female voice must be warm, sincere, and heartfelt, with an ethereal quality that feels like a gentle whisper to the soul. It should be filled with humble submission (khushu') and a tone of love and longing for the divine. The pace must be gentle and flowing, inspiring tranquility and deep spiritual reflection. Ensure flawless Tajweed with a natural, understated melodic rhythm and controlled elongations (Madd), imbuing the delivery with a profound sense of peace and humility: " },
    { id: 'puck-tadwir', name: 'Male: Tadwir (Moderate & Rhythmic)', voice: 'Puck', stylePrompt: "Recite this Quranic verse in a masterful, flowing Tadwir style—a moderate pace between Tarteel and Hadar. The male voice should be resonant, powerful, and confident, yet balanced, with a tone of unwavering faith. The rhythm must be clear and steady, making the recitation easy to follow yet deeply engaging, drawing the listener into a state of contemplation. As a believer confidently proclaiming the truth, the delivery must feature flawless Tajweed, including all rules of Madd, Ghunnah, and articulation, making it ideal for regular prayer and deep reflection: " },
    { id: 'charon', name: 'Male: Tahqiq (Slow & Meticulous)', voice: 'Charon', stylePrompt: "Recite this Quranic verse in a flawless Tahqiq style, using a deep, commanding, yet humble voice filled with the reverence of one who understands the weight of every syllable. The pace must be exceptionally slow, clear, and meticulous, focusing on the perfect articulation (Makharij) of every letter and Tajweed rule. The tone should be deeply reverent and authoritative, as if unpacking the meaning of each word for the listener. Each sound must be given its full measure, and elongations (Madd) executed with precision, as if polishing a precious gem, creating an ideal reference for the study of pronunciation: " },

    // Mujawwad Styles
    { id: 'fenrir', name: 'Male: Mujawwad (Minshawi Inspired)', voice: 'Fenrir', stylePrompt: "Recite this Quranic verse in a masterful Mujawwad style, deeply inspired by the legendary Sheikh Muhammad Siddiq al-Minshawi. The voice must be deeply resonant, conveying a unique and profound sense of huzn (reverent sadness) that pierces the heart. It should be characterized by a pure, slightly nasal timbre that expresses ultimate humility and spiritual focus. Employ varied pacing with masterful, contemplative pauses. The delivery must feature flawless Tajweed and supreme clarity in articulation. Exhibit masterful control over melodic transitions and powerful yet controlled elongations (Madd), with a perfectly executed ghunnah (nasalization) that creates a beautiful, humming resonance. The recitation must be both authoritative and intensely moving, capturing the emotional depth and technical perfection of Sheikh al-Minshawi's legacy while retaining its own spiritual character: " },
    { id: 'puck', name: 'Male: Mujawwad (Abdul Basit Inspired)', voice: 'Puck', stylePrompt: "Recite this Quranic verse in a grand, majestic, and highly melodic Mujawwad style, inspired by the iconic Sheikh Abdul Basit Abdul Samad. The voice must be powerful, golden, and exceptionally controlled, exuding a tone of glorious celebration and divine awe. The delivery must feature flawless Tajweed and legendary breath control, enabling long, uninterrupted, and soaring melodic phrases. Use dynamic and intricate vocal modulation to create emotionally expressive passages, with precise and deeply resonant elongations (Madd). The performance should be captivating and powerful, reflecting the grandeur and virtuosity of Sheikh Abdul Basit's celebrated style: " },

    // Other Styles
    { id: 'puck-warsh', name: 'Male: Warsh (North African Style)', voice: 'Puck', stylePrompt: "Recite this Quranic verse with mastery, strictly following the specific rules of the Warsh 'an Nafi' recitation method. The delivery should be powerful and resonant, with a distinctive, earthy yet spiritual North African vocal timbre that captures the characteristic melodic flow of the style. Maintain flawless Tajweed on every letter, with each rule of pronunciation, merging, and elongation applied with perfection and authenticity, creating a sound that carries the weight of history and is eternally relevant: " },
    { id: 'charon-instructional', name: 'Male: Instructional (For Tajweed Students)', voice: 'Charon', stylePrompt: "Recite this Quranic verse as a patient teacher dedicated to passing on the sacred knowledge of Quranic recitation. The tone should be clear and instructional for teaching Tajweed. The pace must be moderate and deliberate, about 10-15% slower than a typical speaking pace, allowing a student to easily follow. The male voice should be authoritative yet encouraging, with a clear, higher-pitched tone. Articulate every letter and rule with exceptional clarity and textbook perfection, slightly emphasizing points of articulation to serve as an ideal model for a student to imitate, but without unnatural exaggeration of elongations (Madd): " },
];

export const TRANSLATIONS: Translation[] = [
    { id: 'none', name: 'None', translator: 'Display Arabic only', data: null },
    { id: 'en_sahih', name: 'English', translator: 'Sahih International', data: EN_SAHIH_TRANSLATION },
    { id: 'en_qarai', name: 'English', translator: 'Ali Quli Qara\'i', data: EN_QARAI_TRANSLATION },
];